networks:
  vhost-net:
    name: vhost-net
    external: true

services:

  mysite-wp:
    image: wordpress:latest
    build: ./wp
    container_name: mysite-wp
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=mysite-db
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${WP_CORE}:/var/www/html
      - ${WP_CONTENT}:/var/www/html/wp-content
    networks:
      - vhost-net
    labels:
      - "traefik.http.routers.mysite-wp.rule=Host(`${DOMAIN}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.mysite-wp.tls=true"
  
  mysite-db:
    image: mariadb:latest
    container_name: mysite-db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${DB_PATH}:/var/lib/mysql
    networks:
      - vhost-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mysite-db.tls=true"
  
  mysite-db-admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mysite-db-admin
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - PMA_HOST=mysite-db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
     - /sessions
    networks:
      - vhost-net
    labels:
      - "traefik.http.routers.mysite-db-admin.rule=Host(`${DB_DOMAIN}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.mysite-db-admin.tls=true"
